import { useState } from "react";
import Link from "next/link";
import Head from "next/head";

import styles from "@/styles/Home.module.css";
import Modal from "@/components/ui/Modal";

export default function Home() {
  const [openModal, setOpenModal] = useState(false);
  return (
    <>
      {/* Good to include the header on all pages for better SEO, something for later */}
      <Head>
        <title>DiapOneOne</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Modal open={openModal} onClose={() => setOpenModal(!openModal)}>
        <h2>This is the modal test</h2>
      </Modal>
      <section className={styles.card} id="home-content">
        <h1>Welcome To DiapOneOne</h1>
        <br />
        <h2>Your friendly neighbourhood budget checker</h2>
        <br />
        <p>
          Should you buy a diaper or not? Can you afford to buy that cool toy?
          How much do you have left of your budget?
        </p>
        <br />
        <p>
          These questions have haunted parents for millennia but fear not,
          DiapOneOne is here to save the day. Set your budget and see if you
          should go all in or fold your hand for the day!
        </p>
        {/* this is the modal window...working but never used */}
        {/* <button onClick={() => setOpenModal(!openModal)}>Show modal</button> */}
        <Link href="/budget-checker">
          <button>Explore the Budget Checker</button>
        </Link>
      </section>
    </>
  );
}
